LOCAL_PATH := vendor/samsung/J120F
PRODUCT_COPY_FILES += \
$(LOCAL_PATH)/proprietary/lib/hw/gralloc.exynos3.so:system/lib/hw/gralloc.exynos3.so \
$(LOCAL_PATH)/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/hwcomposer.exynos3.so:system/lib/hw/hwcomposer.exynos3.so \
$(LOCAL_PATH)/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
$(LOCAL_PATH)/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
$(LOCAL_PATH)/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
$(LOCAL_PATH)/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
$(LOCAL_PATH)/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
$(LOCAL_PATH)/proprietary/lib/libGLESv3.so:system/lib/libGLESv3.so \
$(LOCAL_PATH)/proprietary/lib/libEGL.so:system/lib/libEGL.so \
$(LOCAL_PATH)/proprietary/lib/libOpenCv.so:system/lib/libOpenCv.so \
$(LOCAL_PATH)/proprietary/lib/libOpenSLES.so:system/lib/libOpenSLES.so \
$(LOCAL_PATH)/proprietary/lib/libion.so:system/lib/libion.so \
$(LOCAL_PATH)/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
$(LOCAL_PATH)/proprietary/usr/idc/mxt540e_i2c.idc:system/usr/idc/mxt540e_i2c.idc \
$(LOCAL_PATH)/proprietary/usr/idc/qwerty2.idc:system/usr/idc/qwerty2.idc \
$(LOCAL_PATH)/proprietary/usr/idc/Synaptics_HID_TouchPad.idc.idc:system/usr/idc/Synaptics_HID_TouchPad.idc \
$(LOCAL_PATH)/proprietary/usr/idc/Synaptics_RMI4_TouchPad_Sensor.idc:system/usr/Synaptics_RMI4_TouchPad_Sensor.idc \
$(LOCAL_PATH)/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Generic.kl:system/usr/keylayout/Generic.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/universal3475-keypad.kl:system/usr/keylayout/universal3475-keypad.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_0b05_Product_4500.kl:system/usr/keylayout/Vendor_0b05_Product_4500.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1bad_Product_f016.kl:system/usr/keylayout/Vendor_1bad_Product_f016.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1bad_Product_f023.kl:system/usr/keylayout/Vendor_1bad_Product_f023.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1bad_Product_f027.kl:system/usr/keylayout/Vendor_1bad_Product_f027.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1bad_Product_f036.kl:system/usr/keylayout/Vendor_1bad_Product_f036.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1d79_Product_0009.kl:system/usr/keylayout/Vendor_1d79_Product_0009.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_04e8_Product_7021.kl:system/usr/keylayout/Vendor_04e8_Product_7021.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_04e8_Product_a000.kl:system/usr/keylayout/Vendor_04e8_Product_a000.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_04e8_Product_a005.kl:system/usr/keylayout/Vendor_04e8_Product_a005.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_04e8_Product_a006.kl:system/usr/keylayout/Vendor_04e8_Product_a006.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_04e8_Product_a009.kl:system/usr/keylayout/Vendor_04e8_Product_a009.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_05ac_Product_0239.kl:system/usr/keylayout/Vendor_05ac_Product_0239.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_05ac_Product_0255.kl:system/usr/keylayout/Vendor_05ac_Product_0255.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_12bd_Product_d015.kl:system/usr/keylayout/Vendor_12bd_Product_d015.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_18d1_Product_2c40.kl:system/usr/keylayout/Vendor_18d1_Product_2c40.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_22b8_Product_093d.kl:system/usr/keylayout/Vendor_22b8_Product_093d.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_045e_Product_028e.kl:system/usr/keylayout/Vendor_045e_Product_028e.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_b32f.kl:system/usr/keylayout/Vendor_046d_Product_b32f.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_b331.kl:system/usr/keylayout/Vendor_046d_Product_b331.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_b332.kl:system/usr/keylayout/Vendor_046d_Product_b332.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_b343.kl:system/usr/keylayout/Vendor_046d_Product_b343.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_b344.kl:system/usr/keylayout/Vendor_046d_Product_b344.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_b501.kl:system/usr/keylayout/Vendor_046d_Product_b501.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_c21d.kl:system/usr/keylayout/Vendor_046d_Product_c21d.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_c21f.kl:system/usr/keylayout/Vendor_046d_Product_c21f.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_c216.kl:system/usr/keylayout/Vendor_046d_Product_c216.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_c219.kl:system/usr/keylayout/Vendor_046d_Product_c219.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_c294.kl:system/usr/keylayout/Vendor_046d_Product_c294.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_c299.kl:system/usr/keylayout/Vendor_046d_Product_c299.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_046d_Product_c532.kl:system/usr/keylayout/Vendor_046d_Product_c532.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_054c_Product_0268.kl:system/usr/keylayout/Vendor_054c_Product_0268.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_0079_Product_0011.kl:system/usr/keylayout/Vendor_0079_Product_0011.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_0461_Product_4dfc.kl:system/usr/keylayout/Vendor_0461_Product_4dfc.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_0583_Product_2060.kl:system/usr/keylayout/Vendor_0583_Product_2060.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1038_Product_1412.kl:system/usr/keylayout/Vendor_1038_Product_1412.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1532_Product_0900.kl:system/usr/keylayout/Vendor_1532_Product_0900.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1689_Product_fd00.kl:system/usr/keylayout/Vendor_1689_Product_fd00.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1689_Product_fd01.kl:system/usr/keylayout/Vendor_1689_Product_fd01.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1689_Product_fe00.kl:system/usr/keylayout/Vendor_1689_Product_fe00.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_1949_Product_0401.kl:system/usr/keylayout/Vendor_1949_Product_0401.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_2378_Product_100a.kl:system/usr/keylayout/Vendor_2378_Product_100a.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_2378_Product_1008.kl:system/usr/keylayout/Vendor_2378_Product_1008.kl \
$(LOCAL_PATH)/proprietary/usr/keylayout/Vendor_2943_Product_0020.kl:system/usr/keylayout/Vendor_2943_Product_0020.kl \
$(LOCAL_PATH)/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.goldfish.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio.primary.universal3475.so:system/lib/hw/audio.primary.universal3475.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio.tms.default.so:system/lib/hw/audio.tms.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
$(LOCAL_PATH)/proprietary/lib/hw/camera.exynos3.so:system/lib/hw/camera.exynos3.so \
$(LOCAL_PATH)/proprietary/lib/hw/camera.goldfish.jpeg.so:system/lib/hw/camera.goldfish.jpeg.so \
$(LOCAL_PATH)/proprietary/lib/hw/camera.goldfish.so:system/lib/hw/camera.goldfish.so \
$(LOCAL_PATH)/proprietary/lib/libarccamera.so:system/lib/libarccamera.so \
$(LOCAL_PATH)/proprietary/lib/libarcsoft_selfie_camera_lite.so:system/lib/libarcsoft_selfie_camera_lite.so \
$(LOCAL_PATH)/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
$(LOCAL_PATH)/proprietary/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
$(LOCAL_PATH)/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
$(LOCAL_PATH)/proprietary/lib/libexynoscameraexternal.so:system/lib/libexynoscameraexternal.so \
$(LOCAL_PATH)/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
$(LOCAL_PATH)/proprietary/lib/libseccamera_jni.so:system/lib/libseccamera_jni.so \
$(LOCAL_PATH)/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
$(LOCAL_PATH)/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
$(LOCAL_PATH)/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
$(LOCAL_PATH)/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
$(LOCAL_PATH)/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
$(LOCAL_PATH)/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
$(LOCAL_PATH)/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
$(LOCAL_PATH)/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
$(LOCAL_PATH)/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
$(LOCAL_PATH)/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
$(LOCAL_PATH)/proprietary/lib/libsomx263dsw.so:system/lib/libsomx263dsw.so \
$(LOCAL_PATH)/proprietary/lib/libsomx264dsw.so:system/lib/libsomx264dsw.so \
$(LOCAL_PATH)/proprietary/lib/libsomxaacd.so:system/lib/libsomxaacd.so \
$(LOCAL_PATH)/proprietary/lib/libsomxaace.so:system/lib/libsomxaace.so \
$(LOCAL_PATH)/proprietary/lib/llibsomxadpcmd.so:system/lib/libsomxadpcmd.so \
$(LOCAL_PATH)/proprietary/lib/libsomxamrd.so:system/lib/libsomxamrd.so \
$(LOCAL_PATH)/proprietary/lib/libsomxcmn.so:system/lib/libsomxcmn.so \
$(LOCAL_PATH)/proprietary/lib/libsomxcore.so:system/lib/libsomxcore.so \
$(LOCAL_PATH)/proprietary/lib/libsomxflacd.so:system/lib/libsomxflacd.so \
$(LOCAL_PATH)/proprietary/lib/libsomxhevcdsw.so:system/lib/libsomxhevcdsw.so \
$(LOCAL_PATH)/proprietary/lib/libsomxmp3d.so:system/lib/libsomxmp3d.so \
$(LOCAL_PATH)/proprietary/lib/libsomxmp4vdsw.so:system/lib/libsomxmp4vdsw.so \
$(LOCAL_PATH)/proprietary/lib/libsomxmp43d.so:system/lib/libsomxmp43d.so \
$(LOCAL_PATH)/proprietary/lib/libsomxnaace.so:system/lib/libsomxnaace.so \
$(LOCAL_PATH)/proprietary/lib/libsomxsr263d.so:system/lib/libsomxsr263d.so \
$(LOCAL_PATH)/proprietary/lib/libsomxvc1dsw.so:system/lib/libsomxvc1dsw.so \
$(LOCAL_PATH)/proprietary/lib/libsomxvencsw.so:system/lib/libsomxvencsw.so \
$(LOCAL_PATH)/proprietary/lib/libsomxvp8d.so:system/lib/libsomxvp8d.so \
$(LOCAL_PATH)/proprietary/lib/libsomxwmad.so:system/lib/libsomxwmad.so \
$(LOCAL_PATH)/proprietary/lib/libsomxwmv7d.so:system/lib/libsomxwmv7d.so \
$(LOCAL_PATH)/proprietary/lib/libsomxwmv8d.so:system/lib/libsomxwmv8d.so \
$(LOCAL_PATH)/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
$(LOCAL_PATH)/proprietary/etc/auto_pair_devlist.conf:system/etc/auto_pair_devlist.conf \
$(LOCAL_PATH)/proprietary/etc/av_performance.conf:system/etc/av_performance.conf \
$(LOCAL_PATH)/proprietary/etc/bt_did.conf:system/etc/bt_did.conf \
$(LOCAL_PATH)/proprietary/etc/bt_stack.conf:system/etc/bt_stack.conf \
$(LOCAL_PATH)/proprietary/etc/iop_bt.db:system/etc/iop_bt.db \
$(LOCAL_PATH)/proprietary/etc/iop_device_list.conf:system/etc/iop_device_list.conf \
$(LOCAL_PATH)/proprietary/etc/bcm43438A1_V0041.0142.hcd:system/etc/bcm43438A1_V0041.0142.hcd \
$(LOCAL_PATH)/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
$(LOCAL_PATH)/proprietary/etc/bcmdhd_apsta.bin:system/etc/bcmdhd_apsta.bin \
$(LOCAL_PATH)/proprietary/etc/bcmdhd_sta.bin:system/etc/bcmdhd_sta.bin \
$(LOCAL_PATH)/proprietary/etc/cred.conf:system/etc/cred.conf \
$(LOCAL_PATH)/proprietary/etc/nvram_mfg.txt:system/etc/nvram_mfg.txt \
$(LOCAL_PATH)/proprietary/etc/nvram_net.txt:system/etc/nvram_net.txt \
$(LOCAL_PATH)/proprietary/etc/p2p_supplicant_overlay.conf:system/etc/p2p_supplicant_overlay.conf \
$(LOCAL_PATH)/proprietary/etc/wpa_supplicant.conf:system/etc/wpa_supplicant.conf \
$(LOCAL_PATH)/proprietary/etc/wpa_supplicant_overlay.conf:system/etc/wpa_supplicant_overlay.conf \
$(LOCAL_PATH)/proprietary/etc/bcmdhd_mfg.bin:system/etc/bcmdhd_mfg.bin \
$(LOCAL_PATH)/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
$(LOCAL_PATH)/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
$(LOCAL_PATH)/proprietary/lib/libril.so:system/lib/libril.so \
$(LOCAL_PATH)/proprietary/lib/librilutils.so:system/lib/librilutils.so \
$(LOCAL_PATH)/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
$(LOCAL_PATH)/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
$(LOCAL_PATH)/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
$(LOCAL_PATH)/proprietary/lib/libstagefright_soft_gsmdec.so:system/lib/libstagefright_soft_gsmdec.so \
$(LOCAL_PATH)/proprietary/lib/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
$(LOCAL_PATH)/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
$(LOCAL_PATH)/proprietary/etc/gps.conf:system/etc/gps.conf \
$(LOCAL_PATH)/proprietary/etc/gps.xml:system/etc/gps.xml \
$(LOCAL_PATH)/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
$(LOCAL_PATH)/proprietary/bin/gpsd:system/bin/gpsd \
$(LOCAL_PATH)/proprietary/bin/gps.cer:system/bin/gps.cer \
$(LOCAL_PATH)/proprietary/lib/hw/sensors.universal3475.so:system/lib/hw/sensors.universal3475.so \
$(LOCAL_PATH)/proprietary/lib/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \
$(LOCAL_PATH)/proprietary/bin/sensorservice:system/bin/sensorservice \
$(LOCAL_PATH)/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so
